
@body = {"login" : "joeparc@hotmail.com" , "password" : "JoshAdmin101"}

GET http://joe.api/flipper/1
###

PUT http://joe.api/flipper/1

{{body}}
###
POST http://joe.api/flipper/5

{{body}}
###
POST http://joe.api/auth/login

{{body}}